-- MySQL Script generated by MySQL Workbench
-- 06/04/15 23:16:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema keystrokedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `keystrokedb` ;

-- -----------------------------------------------------
-- Schema keystrokedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `keystrokedb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `keystrokedb` ;

-- -----------------------------------------------------
-- Table `keystrokedb`.`password_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keystrokedb`.`password_table` ;

CREATE TABLE IF NOT EXISTS `keystrokedb`.`password_table` (
  `idpass` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(12) NOT NULL,
  `pass_valid` TINYINT(1) NOT NULL DEFAULT 0,
  `date` DATE NULL,
  `time` TIME(3) NULL,
  `access` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idpass`),
  UNIQUE INDEX `idpass_UNIQUE` (`idpass` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keystrokedb`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keystrokedb`.`languages` ;

CREATE TABLE IF NOT EXISTS `keystrokedb`.`languages` (
  `idlang` INT NOT NULL AUTO_INCREMENT,
  `firstlang` VARCHAR(45) NULL,
  `seclang` VARCHAR(45) NULL,
  `thirdlang` VARCHAR(45) NULL,
  PRIMARY KEY (`idlang`),
  UNIQUE INDEX `idlang_UNIQUE` (`idlang` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keystrokedb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keystrokedb`.`user` ;

CREATE TABLE IF NOT EXISTS `keystrokedb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(12) NOT NULL,
  `mac` VARCHAR(17) NULL,
  `gender` CHAR(1) NULL,
  `age` INT NULL,
  `position_pass` INT NULL,
  `session_number` INT NULL,
  `password_table_idpass` INT NULL,
  `languages_idlang` INT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC),
  UNIQUE INDEX `mac_UNIQUE` (`mac` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_password_table1_idx` (`password_table_idpass` ASC),
  INDEX `fk_user_languages1_idx` (`languages_idlang` ASC),
  CONSTRAINT `fk_user_password_table1`
    FOREIGN KEY (`password_table_idpass`)
    REFERENCES `keystrokedb`.`password_table` (`idpass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_languages1`
    FOREIGN KEY (`languages_idlang`)
    REFERENCES `keystrokedb`.`languages` (`idlang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keystrokedb`.`exp_pass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keystrokedb`.`exp_pass` ;

CREATE TABLE IF NOT EXISTS `keystrokedb`.`exp_pass` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `expass` VARCHAR(45) NOT NULL,
  `num_rep` INT NULL DEFAULT 1,
  UNIQUE INDEX `num_UNIQUE` (`num` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keystrokedb`.`exp_password_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keystrokedb`.`exp_password_table` ;

CREATE TABLE IF NOT EXISTS `keystrokedb`.`exp_password_table` (
  `idpasstable` INT NOT NULL AUTO_INCREMENT,
  `pos_pass` INT NULL DEFAULT 1,
  `expass` VARCHAR(45) NULL,
  `exp_password_tablecol` VARCHAR(45) NULL,
  `date` DATE NULL,
  `time` TIME(3) NULL,
  `session_number` INT NULL DEFAULT 1,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idpasstable`),
  UNIQUE INDEX `idpasstable_UNIQUE` (`idpasstable` ASC),
  INDEX `fk_exp_password_table_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_exp_password_table_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `keystrokedb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keystrokedb`.`key_expass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keystrokedb`.`key_expass` ;

CREATE TABLE IF NOT EXISTS `keystrokedb`.`key_expass` (
  `idkey` INT NOT NULL AUTO_INCREMENT,
  `keyname` VARCHAR(45) NULL,
  `keydown` TIME(3) NULL,
  `keyup` TIME(3) NULL,
  `press_duration` TIME(3) NULL,
  `exp_password_table_idpasstable` INT NOT NULL,
  PRIMARY KEY (`idkey`),
  UNIQUE INDEX `idkey_UNIQUE` (`idkey` ASC),
  INDEX `fk_key_expass_exp_password_table1_idx` (`exp_password_table_idpasstable` ASC),
  CONSTRAINT `fk_key_expass_exp_password_table1`
    FOREIGN KEY (`exp_password_table_idpasstable`)
    REFERENCES `keystrokedb`.`exp_password_table` (`idpasstable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
